env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'require-jsdoc': off,
  'no-invalid-this': off,
  'comma-dangle': off,
  'object-curly-spacing': ['error', 'always'],
  '@typescript-eslint/ban-ts-ignore': off,
  'react/display-name': off,
  'max-len': ['error', { 'code': 100 }],
  'arrow-body-style': ['warn', 'as-needed'],
  '@typescript-eslint/camelcase': warn
}
